### ISSUE TITLE
Internal Server Error testing "/api/v1/3gpp-monitoring-event/v1/{scsAsId}/subscriptions" from SWAGGER

### ISSUE THREAD

**Issue by dcamps** [medianetlab/NEF_emulator#79]
Hi all,

I have installed the NEF emulator in standalone mode. In my .env I have:
EXTERNAL_NET=false
USE_PUBLIC_KEY_VERIFICATION=false

I am trying to test the monitoring event API through SWAGGER. The steps I follow are:

1) Authorize SWAGGER setting:
username: admin@my-email.com
password: pass

2) When I call "GET /api/v1/3gpp-monitoring-event/v1/myNetapp/subscriptions", it correctly returns 204, as no 

3) I try to create a registration with: "POST /api/v1/3gpp-monitoring-event/v1/myNetapp/subscriptions", and the default body:
{
  "externalId": "123456789@domain.com",
  "notificationDestination": "http://localhost:80/api/v1/utils/monitoring/callback",
  "monitoringType": "LOCATION_REPORTING",
  "maximumNumberOfReports": 1,
  "monitorExpireTime": "2023-05-25T19:16:48.509Z",
  "maximumDetectionTime": 1,
  "reachabilityType": "DATA"
}

Here I get a 500 and internal server error, with the error trace that I paste below. I would appreciate any insight in how to debug this issue.

BR

Daniel

nef_emulator-backend-1        | INFO:     172.18.0.5:43012 - "POST /api/v1/3gpp-monitoring-event/v1/myNetapp/subscriptions HTTP/1.0" 500 Internal Server Error
nef_emulator-reverse_proxy-1  | 192.168.13.1 - - [23/May/2023:19:37:41 +0000] "POST /nef/api/v1/3gpp-monitoring-event/v1/myNetapp/subscriptions HTTP/1.1" 500 21 "https://192.168.13.2:4443/nef/docs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
nef_emulator-backend-1        | ERROR:    Exception in ASGI application
nef_emulator-backend-1        | Traceback (most recent call last):
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
nef_emulator-backend-1        |     result = await app(self.scope, self.receive, self.send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
nef_emulator-backend-1        |     return await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
nef_emulator-backend-1        |     await super().__call__(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
nef_emulator-backend-1        |     await self.middleware_stack(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, _send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in __call__
nef_emulator-backend-1        |     await response(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 253, in __call__
nef_emulator-backend-1        |     async with anyio.create_task_group() as task_group:
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
nef_emulator-backend-1        |     raise exceptions[0]
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 256, in wrap
nef_emulator-backend-1        |     await func()
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 245, in stream_response
nef_emulator-backend-1        |     async for chunk in self.body_iterator:
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 58, in body_stream
nef_emulator-backend-1        |     raise app_exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
nef_emulator-backend-1        |     await self.app(scope, request.receive, send_stream.send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
nef_emulator-backend-1        |     await self.simple_response(scope, receive, send, request_headers=headers)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, sender)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nef_emulator-backend-1        |     raise e
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
nef_emulator-backend-1        |     await route.handle(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
nef_emulator-backend-1        |     await super().__call__(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
nef_emulator-backend-1        |     await self.middleware_stack(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, _send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, sender)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nef_emulator-backend-1        |     raise e
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
nef_emulator-backend-1        |     await route.handle(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
nef_emulator-backend-1        |     response = await func(request)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
nef_emulator-backend-1        |     raw_response = await run_endpoint_function(
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
nef_emulator-backend-1        |     return await run_in_threadpool(dependant.call, **values)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
nef_emulator-backend-1        |     return await anyio.to_thread.run_sync(func, *args)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
nef_emulator-backend-1        |     return await get_asynclib().run_sync_in_worker_thread(
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
nef_emulator-backend-1        |     return await future
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
nef_emulator-backend-1        |     result = context.run(func, *args)
nef_emulator-backend-1        |   File "/app/./app/api/api_v1/endpoints/monitoringevent.py", line 91, in create_subscription
nef_emulator-backend-1        |     ccf_logs(http_request, json_response, "service_monitoring_event.json", token_payload.get("sub"))
nef_emulator-backend-1        | AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dcamps** [comment]
Hi all,

I have realized the error occurs in: ./backend/app/app/api/api_v1/endpoints/monitoringevent.py 

Specifically, within this block of code:

        #CAPIF Core Function Logging Service
        try:
            response = http_response.body.decode("utf-8")
            json_response = {}
            json_response.update({"response" : response})
            json_response.update({"status_code" : str(http_response.status_code)})
            ccf_logs(http_request, json_response, "service_monitoring_event.json", token_payload.get("sub"))
        except TypeError as error:
            logging.critical(f"Error: {error}")


However, I have not deployed CAPIF in my setup. Do I need it? Can the NEF emulator work in standalone mode without CAPIF?

BR

Daniel

**Comment by JFrgs** [comment]
Hello Daniel,

I have fixed the error catching the Attribute Error exception when you use NEF without CAPIF. 
see commit #cca77cc 

Please try again to ensure that the issue is resolved.

**Comment by dcamps** [comment]
Hi,

Yes, the commit seems to solve the issue I was having and I could verify that I can create a subscription.

However, I observed that I still have the problem if I try to create a subscription with "maximumNumberOfReports" bigger than 1. For example the following payload gives me a 500:

{
  "externalId": "10002@domain.com",
  "notificationDestination": "http://localhost:80/api/v1/utils/monitoring/callback",
  "monitoringType": "LOCATION_REPORTING",
  "maximumNumberOfReports": 2,
  "monitorExpireTime": "2023-05-25T14:27:22.491Z",
  "maximumDetectionTime": 1,
  "reachabilityType": "DATA"
}

It is interesting though that after I get the 500, the subscription appears to be created, i.e. I can get it with the GET endpoint. I paste below the error trace, which seems to be again in the logging function.

BR

Daniel

nef_emulator-backend-1        | INFO:     172.18.0.5:59888 - "POST /api/v1/3gpp-monitoring-event/v1/myNetapp/subscriptions HTTP/1.0" 500 Internal Server Error
nef_emulator-reverse_proxy-1  | 192.168.13.1 - - [24/May/2023:14:42:19 +0000] "POST /nef/api/v1/3gpp-monitoring-event/v1/myNetapp/subscriptions HTTP/1.1" 500 21 "https://192.168.13.2:4443/nef/docs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
nef_emulator-backend-1        | ERROR:    Exception in ASGI application
nef_emulator-backend-1        | Traceback (most recent call last):
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
nef_emulator-backend-1        |     result = await app(self.scope, self.receive, self.send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
nef_emulator-backend-1        |     return await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
nef_emulator-backend-1        |     await super().__call__(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
nef_emulator-backend-1        |     await self.middleware_stack(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, _send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in __call__
nef_emulator-backend-1        |     await response(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 253, in __call__
nef_emulator-backend-1        |     async with anyio.create_task_group() as task_group:
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
nef_emulator-backend-1        |     raise exceptions[0]
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 256, in wrap
nef_emulator-backend-1        |     await func()
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 245, in stream_response
nef_emulator-backend-1        |     async for chunk in self.body_iterator:
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 58, in body_stream
nef_emulator-backend-1        |     raise app_exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
nef_emulator-backend-1        |     await self.app(scope, request.receive, send_stream.send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
nef_emulator-backend-1        |     await self.simple_response(scope, receive, send, request_headers=headers)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, sender)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nef_emulator-backend-1        |     raise e
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
nef_emulator-backend-1        |     await route.handle(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
nef_emulator-backend-1        |     await super().__call__(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
nef_emulator-backend-1        |     await self.middleware_stack(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, _send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, sender)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nef_emulator-backend-1        |     raise e
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
nef_emulator-backend-1        |     await route.handle(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
nef_emulator-backend-1        |     response = await func(request)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
nef_emulator-backend-1        |     raw_response = await run_endpoint_function(
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
nef_emulator-backend-1        |     return await run_in_threadpool(dependant.call, **values)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
nef_emulator-backend-1        |     return await anyio.to_thread.run_sync(func, *args)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
nef_emulator-backend-1        |     return await get_asynclib().run_sync_in_worker_thread(
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
nef_emulator-backend-1        |     return await future
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
nef_emulator-backend-1        |     result = context.run(func, *args)
nef_emulator-backend-1        |   File "/app/./app/api/api_v1/endpoints/monitoringevent.py", line 180, in create_subscription
nef_emulator-backend-1        |     ccf_logs(http_request, json_response, "service_monitoring_event.json", token_payload.get("sub"))
nef_emulator-backend-1        | AttributeError: 'NoneType' object has no attribute 'get'
nef_emulator-backend-1        | ERROR:uvicorn.error:Exception in ASGI application
nef_emulator-backend-1        | Traceback (most recent call last):
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
nef_emulator-backend-1        |     result = await app(self.scope, self.receive, self.send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
nef_emulator-backend-1        |     return await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
nef_emulator-backend-1        |     await super().__call__(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
nef_emulator-backend-1        |     await self.middleware_stack(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, _send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in __call__
nef_emulator-backend-1        |     await response(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 253, in __call__
nef_emulator-backend-1        |     async with anyio.create_task_group() as task_group:
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
nef_emulator-backend-1        |     raise exceptions[0]
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 256, in wrap
nef_emulator-backend-1        |     await func()
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 245, in stream_response
nef_emulator-backend-1        |     async for chunk in self.body_iterator:
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 58, in body_stream
nef_emulator-backend-1        |     raise app_exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
nef_emulator-backend-1        |     await self.app(scope, request.receive, send_stream.send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
nef_emulator-backend-1        |     await self.simple_response(scope, receive, send, request_headers=headers)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, sender)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nef_emulator-backend-1        |     raise e
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
nef_emulator-backend-1        |     await route.handle(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
nef_emulator-backend-1        |     await super().__call__(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
nef_emulator-backend-1        |     await self.middleware_stack(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, _send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
nef_emulator-backend-1        |     raise exc
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, sender)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nef_emulator-backend-1        |     raise e
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
nef_emulator-backend-1        |     await route.handle(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
nef_emulator-backend-1        |     await self.app(scope, receive, send)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
nef_emulator-backend-1        |     response = await func(request)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
nef_emulator-backend-1        |     raw_response = await run_endpoint_function(
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
nef_emulator-backend-1        |     return await run_in_threadpool(dependant.call, **values)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
nef_emulator-backend-1        |     return await anyio.to_thread.run_sync(func, *args)
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
nef_emulator-backend-1        |     return await get_asynclib().run_sync_in_worker_thread(
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
nef_emulator-backend-1        |     return await future
nef_emulator-backend-1        |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
nef_emulator-backend-1        |     result = context.run(func, *args)
nef_emulator-backend-1        |   File "/app/./app/api/api_v1/endpoints/monitoringevent.py", line 180, in create_subscription
nef_emulator-backend-1        |     ccf_logs(http_request, json_response, "service_monitoring_event.json", token_payload.get("sub"))
nef_emulator-backend-1        | AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dcamps** [comment]
Hi @JFrgs, 

There was a place where the code for handling the error was not added. I paste here a patch to fix the error. Can you merge it to main?

````
--- a/backend/app/app/api/api_v1/endpoints/monitoringevent.py
+++ b/backend/app/app/api/api_v1/endpoints/monitoringevent.py
@@ -180,6 +180,8 @@ def create_subscription(
             ccf_logs(http_request, json_response, "service_monitoring_event.json", token_payload.get("sub"))
         except TypeError as error:
             logging.error(f"Error: {error}")
+        except AttributeError as error:
+            logging.error(f"Error: {error}")

         return http_response
     elif (item_in.monitoringType == "LOSS_OF_CONNECTIVITY" or item_in.monitoringType == "UE_REACHABILITY") and item_in.maximumNumberOfReports == 1:
diff --git a/env-file-for-local.dev b/env-file-for-local.dev
````


BR

Daniel

**Comment by JFrgs** [comment]
This issue is resolved in the latest Release `v2.2.1`

Best,
Dimitris
